<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use PHPMailer\PHPMailer\Exception;
use PHPMailer\PHPMailer\PHPMailer;

class cvController extends Controller
{
    public function sendcv(Request $request)
    {

        $name= $request->name;
        $email = $request->email;
        $phone = $request->phone;
        $msg = $request->msg;
        $subject = $request->subject;
        $attachments = $request->attachments;







        $emailb = "hello@directpay.lk";
        $mail = new PHPMailer(true);
        date_default_timezone_set('Asia/Colombo');
        $tdate= date("Y/m/d");
        $ttime = date('H.i A ');
        $sub = $request->name." has sent a application for $subject";
        $mail->isSMTP();
        $mail->CharSet = "utf-8";
        $mail->SMTPAuth = true;
        $mail->SMTPSecure = "ssl";
        $mail->Host = "mail.directpay.lk";
        $mail->Port = 465;
        $mail->Username = "kasun@directpay.lk";
        $mail->Password = "getmein123";
        $mail->setFrom('kasun@directpay.lk', 'DirectPay');
        $mail->Subject =  $sub;
        //$mail->AddCC('hello@directpay.lk', 'DirectPay');
        $mail->AddCC('simulatorkasun@gmail.com', 'DirectPay CV');
        $mail->MsgHTML("<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>
            <html xmlns='http://www.w3.org/1999/xhtml'>
            <head><meta http-equiv='Content-Type' content='text/html; charset=utf-8'>

            <meta name='viewport' content='width=device-width, initial-scale=1.0'/>
            </head>
            <body style='margin: 0; padding: 0;'>
            <table border='0' cellpadding='0' cellspacing='0' width='100%'>
            <tr>
               <td style='padding: 10px 0 30px 0;'>
                   <table align='center' border='0' cellpadding='0' cellspacing='0' width='600' style='border: 1px solid #cccccc; border-collapse: collapse;'>
                       <tr>
                           <td align='center'>
                               <img src='https://res.cloudinary.com/directpay/image/upload/v1621226435/Untitled-1-min_jxaywc.png' alt='Email' width='600' height='350' style='display: block;' />
                           </td>
                       </tr>
                       <tr>
                           <td bgcolor='#ffffff' style='padding: 40px 30px 40px 30px;'>
                               <table border='0' cellpadding='0' cellspacing='0' width='100%'>
                                   <tr>
                                       <td style='padding: 20px 0 30px 0; color: #2f2e2e; font-family: Arial, sans-serif; font-size: 16px; line-height: 20px;'>
                                         <h3>New application for $subject</h3><br /><br />

                                         <strong>applicant Name :</strong>$name<br />
                                         <strong>applicant email :</strong>$email<br />
                                         <strong>Position Applied :</strong>$subject<br />
                                         <strong>Description :</strong>$msg<br />
                                         <strong>Phone Number :</strong>$phone<br />
                                         <strong>Attachments : </strong>$attachments<br/>





                            <br /><br /><br /><br />
                                       </td>
                                   </tr>

                               </table>
                           </td>
                       </tr>
                       <tr>
                       <table>
                           <td bgcolor='#fff' style='padding: 30px 30px 30px 30px;'>
                               <table border='0' cellpadding='0' cellspacing='0' width='100%'>
                               <tr>
                               <td style='color: #ffffff; font-family: Arial, sans-serif; font-size: 14px;' width='100%'>

                                 <center><font color='#000'>This mail generated by DirectPay.lk</font></font></center>
                                 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                 </td>
                               </tr>
                               </table>
                           </td>
                       </tr>
                   </table>
               </td>
            </tr>
            </table>

            </body>
            </html>");
        $mail->addAddress($emailb, "Admin");
        $mail->send();
        return redirect()->back();


    }
}
